### PR TITLE
Add `noError` helper.

### PR DESCRIPTION
**Pull request by mattcollier**
My experiments show that calling `done(err)` does not produce any result different from `throw err`.  Also, afaik the only way to get the entire error details is to JSON.stringify it as in the PR.  This is modeled after the manual process I've been using.

### CODE REVIEW

**Comment by mattcollier** [comment]
Also, we should soon see a better way to assert the existence of an error in chai: https://github.com/chaijs/chai/issues/930

**Comment by davidlehn** [comment]
Got an example of how that is used?

**Comment by mattcollier** [comment]
@davidlehn 
```
  it('validates a proper config', done => {
    const testConfig = mockData.ledgers.alpha.config.input[0].eventValidator[0];
    brValidator.validateConfiguration(testConfig, err => {
      noError(err);
      // instead of
      // should.not.exist(err);
      done();
    });
  });
```

**Comment by mattcollier** [comment]
@davidlehn since you may have missed the conversation @dlongley and I have had on this topic.

the `should.not.exist(err)` method is not very helpful when a test that should not be returning an error starts returning an error.  It says `AssertionError: expected { Object (name, message, ...) } to not exist`.  In order to diagnose the problem, one must perform surgery on the test itself to add additional logging.

**Comment by dlongley** [comment]
I think this function is fine other than it's confusing name (it's confusing to me right now anyway). Why is it called `noError`? Maybe `logError` or `logAndThrow` would be better given its implementation? Or whatever other clever name.

**Comment by mattcollier** [comment]
@dlongley your `assertNoError` is what I was aiming for.  So if that name is agreeable, we can run with it.

As I thought about names, one thing I was hoping (but failed) to achieve was some way of indicating in the name that this was *not* part of node `assert` or `chai` etc.  When I was getting started with the test framework I found it difficult to know where various globals where coming from (bedrock, mocha, chai, protractor, etc).  So, what about `brAssertNoError` or something along those lines?

**Comment by dlongley** [comment]
> When I was getting started with the test framework I found it difficult to know where various globals where coming from...

I think that's a general problem we can't easily solve. I'd rather not introduce a prefixed naming convention when the convention seems to be "it doesn't matter where these things come from" -- which I agree is a point of frustration when you want to figure out how to use them properly. IMO, it would be better to have namespaces like `global.mocha` and `global.chai` and `global.bedrock` for these things, but that would just fly in the face of how other people write tests and cause confusion on the other end (e.g. "Why do my mocha tests look different from all the other online examples?" and so on).

**Comment by mattcollier** [comment]
@davidlehn @dlongley any objections to `assertNoError`?

**Comment by davidlehn** [comment]
There is a BedrockError.toObject() call.  It might be overkill for testing, but maybe try the following and see if the output is more helpful:
```js
global.noError = (err) => {
  if(err) {
    const obj = err instanceof BedrockError ? err.toObject() : err;
    console.error(
      'An unexpected error occurred:', JSON.stringify(obj, null, 2));
    throw err;
  }
};
```

**Comment by mattcollier** [comment]
@dlongley ready for another pass.  Successfully ran some tests using this helper.

**Pull request merged**
