### PR TITLE
Add `bedrock.util.delay` API.

### PR DESCRIPTION
**Pull request by mattcollier**

### CODE REVIEW

**Comment by dlongley** [comment]
@mattcollier, is there a reason why we need this in bedrock vs. as a separate library?

**Comment by mattcollier** [comment]
@dlongley both `delay` (sleep) and `uuid` are commonly used functions.  I see bedrock as a curated collection of helpers.  Of course it's easier to manage dependencies if they are in 50 different modules.  So, for instance, we've recently started using `uuid-random` which is superior to the `uuid` dependency we've been using.  If we had already been using `bedrock.util.uuid` then we would be able to silently replace that dependency in all the places.

**Comment by dlongley** [comment]
I have mixed feelings about this, but will approve. Your point about managing dependencies is good -- but at the same time, we don't want to create a monolith that needs to be updated in order for other modules to get updates. We both want to decentralize the ability the upgrade and centralize "default upgrades".

**Comment by davidlehn** [comment]
Pardon, this fell off my radar earlier.  I do have management concerns about a "curated collection of helpers" that is a dependency of countless other packages at this point.  If any of those exported helpers have a major semver type of change, then we have to also bump bedrock itself.  A major bedrock version bump is so difficult at this point that we specifically don't make bedrock changes because of it.  I'm afraid of the longer term consequences of adding to the problem.  Perhaps an improved design should be discussed in another issue.

**Comment by dlongley** [comment]
@davidlehn, I share your concerns. Please open another issue for it.

**Pull request merged**
